name: Auto Review and Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  quality-review:
    name: Quality Review
    runs-on: ubuntu-latest
    outputs:
      quality_result: ${{ steps.quality-check.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run quality check
        id: quality-check
        run: |
          # Temporary echo for testing
          echo "result=GOOD" >> $GITHUB_OUTPUT
          echo "Quality check completed"

  auto-merge:
    name: Auto Merge
    needs: quality-review
    if: ${{ needs.quality-review.outputs.quality_result == 'GOOD' }}
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "Auto-merged via quality check"
          MERGE_DELETE_BRANCH: true

  reject-pr:
    name: Reject PR
    needs: quality-review
    if: ${{ needs.quality-review.outputs.quality_result != 'GOOD' }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '❌ Quality check failed. Please review and update your changes.'
            })
