name: Code Quality Review & Testing

# Define required permissions
permissions:
  contents: write
  issues: write
  pull-requests: write

# Only trigger on pull request events
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Call OpenHands reusable workflow at the job level
  quality-review:
    uses: All-Hands-AI/OpenHands/.github/workflows/openhands-resolver.yml@main
    with:
      macro: "@quality-check"
      max_iterations: 10
      llm_model: "anthropic/claude-3-5-sonnet-20241022"
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}

  # Run tests after quality review
  run-tests:
    needs: quality-review
    runs-on: ubuntu-latest
    if: needs.quality-review.outputs.quality_result == 'GOOD'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root
          
      - name: Run tests
        run: |
          poetry run pytest --forked -n auto -svv ./tests/unit

  # Auto-merge if everything passes
  auto-merge:
    needs: [quality-review, run-tests]
    runs-on: ubuntu-latest
    if: needs.quality-review.outputs.quality_result == 'GOOD'
    steps:
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "Auto-merged via AI code quality check"
          MERGE_DELETE_BRANCH: true
          MERGE_RETRIES: 3
          MERGE_RETRY_SLEEP: 10000

  # Post rejection comment if quality check fails
  reject-pr:
    needs: quality-review
    runs-on: ubuntu-latest
    if: needs.quality-review.outputs.quality_result != 'GOOD'
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const message = `❌ Code quality review failed. Please address the following:
            
            1. Review the quality review feedback
            2. Make necessary improvements
            3. Update the pull request
            
            The workflow will automatically re-run when you push new changes.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
